### ISSUE TITLE
Error with could not open resouce config / failed to load resource roleplay

### ISSUE THREAD

**Issue by Systenadmin** [GuilhermeTrevizani/roleplay-server#4]
Hello, I wanted to look at the script and I see the following error:

how can i fix it? 
![image](https://github.com/GuilhermeTrevizani/roleplay-server/assets/45108210/4aba6bb6-3fee-44a4-a85d-75849632148a)

**Comment by GuilhermeTrevizani** [comment]
Please try with new commited changes.
